services:
  app_my_postgres:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.my_postgres
    environment:
      CONNECTION_URI: $APP_MY_POSTGRES_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_MY_POSTGRES_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_MY_POSTGRES_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MY_POSTGRES_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 6016:8080
